Front end Random Message
Bishoy-Samwel/react-front-end pull request #1
Opened 2022-01-21 17:19 UTC by Bishoy-Samwel

Users can extract the random messages from API 
[Back-end](https://github.com/Bishoy-Samwel/Rails-React-Intro)

2022-01-21 19:02 UTC, bimbolabuari requested changes
Hi Team, 

You have done a good job so far 🚀  

## Highlights 🎉 
- Create a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
- Your PR provide your a link to the Rails API (backend app)


There are some issues that you still need to work on to go to the next project but you are almost there! 🎉 

## Required Changes ♻️
- As required, Let's create an `app` component with react-router

>![image](https://user-images.githubusercontent.com/66112760/150584866-1cd8b5b3-a4cc-4d16-b03c-31ccaf236fcc.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

--------


_Reviewed by  @bimbolabuari_

2022-01-21 19:02 UTC, bimbolabuari commented on src/configureStore.js
> +  console.log(action.type, 'request');
[Optional] Kindly remove all console logs from your code, to make it look more professional ✊

2022-01-21 20:20 UTC, oloomoses requested changes
Hi @Bishoy-Samwel, 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly fix the linter failing check before submitting for another review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-21 20:20 UTC, oloomoses commented on src/index.js
> +          </Routes>
- [ ] Routing should be done in the `App` component and not `index.js`. Kindly create an App component as suggested in the previous review and do the routing from there.

2022-01-21 20:20 UTC, oloomoses commented on src/configureStore.js
> +  console.log(action.type, 'request');
- [ ] Kindly remove the console log statement as suggested. It is ugly and exposes your data.

2022-01-21 20:20 UTC, oloomoses commented on src/message.jsx
> +};
- [ ] Kindly remove the console log statement as suggested. It is ugly and exposes your data.

2022-01-22 13:34 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @Bishoy-Samwel, 

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-22 13:35 UTC, merged